### ISSUE TITLE
Determine the data set latest version within a major version

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/eesyapi#26]
## Is your feature request related to a problem? Please describe.
A few of the functions will need to know the latest data set version available within a given major release, i.e. if we want the latest version of v1.x.x or v2.x.x etc, go and check what that is.

## Describe the solution you'd like
Something that takes the major version number and returns e.g. v1.1.5 for use by query_dataset(), get_meta(), etc.

**Comment by cjrace** [comment]
Think we need this for the closed testing of API so moving into that milestone instead of the testing sweep one

**Comment by cjrace** [comment]
> Think we need this for the closed testing of API so moving into that milestone instead of the testing sweep one

Changing my mind on this, don't think it's critical to testing.

I'm also doubting whether it should live in the package at all. Absolutely we could do this here, though I think actually we should look at whether we can set a default behaviour in the service itself that does this, so everyone, not just users of this package get it. Going to close this for now and talk more about it next week.
