### ISSUE TITLE
Final clean up on attendance test data

### ISSUE THREAD

**Issue by rmbielby** [dfe-analytical-services/eesyapi#42]
## Describe the bug
The test data still has a handful of elements that need cleaning up to make it clearer for users what the content is.

## How to reproduce

In the attendance data, attendance_status and attendance_type have items that are set to Not determined. These need clarifying with the attendance team and setting to appropriate values.

## Expected behaviour
All filter items in the test data have an understandable entry.

**Comment by cjrace** [comment]
When ready, replace the attendance files in here - https://educationgovuk.sharepoint.com/:f:/r/sites/lveesfa00074/Data%20Insights%20and%20Statistics%20Division/Statistics%20Services%20Unit/Explore%20education%20statistics%20platforms/Public%20API/API%20test%20data/[end_users](https://educationgovuk.sharepoint.com/:f:/r/sites/lveesfa00074/Data%20Insights%20and%20Statistics%20Division/Statistics%20Services%20Unit/Explore%20education%20statistics%20platforms/Public%20API/API%20test%20data/end_users?csf=1&web=1&e=qUNNWY)?csf=1&web=1&e=qUNNWY

Currently I have the attendance file as v1.1 and then then same file with 2 weeks less data as v1.0, should be easy to recreate with the updated cleaned versions

**Comment by rmbielby** [comment]
I've uploaded the files as zip archives to the folder:
attendance_full-year_202324.zip
attendance_penultimate-release_202324.zip
