### ISSUE TITLE
Tidy up attainment example data files

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/eesyapi#52]
We want a tidied up version of an attainment file as a test example for the API testing. Ideally we'd have two versions, the second of which having an extra year of data.

Once ready both versions should be screened and dropped into this folder ready to be uploaded for testing.

https://educationgovuk.sharepoint.com/:f:/r/sites/lveesfa00074/Data%20Insights%20and%20Statistics%20Division/Statistics%20Services%20Unit/Explore%20education%20statistics%20platforms/Public%20API/API%20test%20data/[end_users](https://educationgovuk.sharepoint.com/:f:/r/sites/lveesfa00074/Data%20Insights%20and%20Statistics%20Division/Statistics%20Services%20Unit/Explore%20education%20statistics%20platforms/Public%20API/API%20test%20data/end_users?csf=1&web=1&e=qUNNWY)?csf=1&web=1&e=qUNNWY

We don't need to include lots of examples, but it should form one of the three example IDs available on test as a part of #39

**Comment by rmbielby** [comment]
Added the files in the following zip archives:
- ks5_cscp_eesp-version.zip
- ks5_cscp_eesp-nodisadv-version.zip (breaking copy with filter removed)
